/// Jenkinsfile for Blueverse Backend
def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
    'UNSTABLE': 'warning'
]
def MESSAGES_MAP = [
    'SUCCESS': "success",
    'FAILURE': "failed",
    'UNSTABLE': "unstable"
]
pipeline {
    agent any
    options {
        // fail build if takes more than 30 minutes, mark reason as build timeout
        timeout(time: 15, unit: 'MINUTES')
        // Keep the 10 most recent builds
        buildDiscarder(logRotator(numToKeepStr: '10'))
        // Don't run any stage if found to be unstable
        skipStagesAfterUnstable()
    }
    environment {
        DISPLAY_SERVICE_NAME    = 'Blueverse Backend'
        BRANCH_NAME             = sh(script: "echo ${env.BRANCH_NAME}", returnStdout: true).trim()
        DO_SERVER               = credentials('nfx-dev-server')

        BLUEVERSE_PROD          = credentials('bluverse-prod-server-ip')
    }
    stages {
        stage('SCM Checkout') {
            steps {
                checkout scm
            }
        }
        stage("Environment Variables") {
            steps {
                sh "printenv"
            }
        }
        stage('Deploy to Digital Ocean') {
            parallel {
                stage('Deploying to Environment') {
                    when {
                        expression { return BRANCH_NAME == 'develop' || BRANCH_NAME == 'qa' || BRANCH_NAME == 'staging' }
                    }
                    steps {
                        sshagent(credentials : ['nfx-dev-server-do']) {
                            sh 'ssh -o StrictHostKeyChecking=no ubuntu@${DO_SERVER} uptime'
                            sh """ ssh ubuntu@${DO_SERVER} "cd projects/blueverse/${BRANCH_NAME}/; git reset --hard && git pull origin ${BRANCH_NAME} && chmod +x ./script.sh && ./script.sh ${BRANCH_NAME}" """
                        }
                    }
                }
                stage('Deploying to Blueverse-stage') {
                    when {
                        expression { return  BRANCH_NAME == 'stage-prod' }
                    }
                    steps {
                        sshagent(credentials : ['bluverse-prod-server']) {
                            sh 'ssh -o StrictHostKeyChecking=no ubuntu@52.45.75.61 uptime'
                            sh """ ssh ubuntu@52.45.75.61 "cd blueverse/${BRANCH_NAME}/; git reset --hard && git pull origin ${BRANCH_NAME} && chmod +x ./script.sh && ./script.sh ${BRANCH_NAME}" """
                        }
                    }
                }
                stage('Deploying to Blueverse-prod') {
                    when {
                        expression { return BRANCH_NAME == 'master' }
                    }
                    steps {
                        sshagent(credentials : ['bluverse-prod-server']) {
                            sh 'ssh -o StrictHostKeyChecking=no ubuntu@${BLUEVERSE_PROD} uptime'
                            sh """ ssh ubuntu@${BLUEVERSE_PROD} "cd blueverse/${BRANCH_NAME}/; git reset --hard && git pull origin ${BRANCH_NAME} && chmod +x ./script.sh && ./script.sh ${BRANCH_NAME}" """
                        }
                    }
                }
            }
        }
    }
}
