const config = {
  serverConfig: {
    PORT: process.env.SERVER_PORT,
    env: process.env.NODE_ENV,
  },
  dbConfig: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: 'postgres',
    define: {
      freezeTableName: true,
      underscored: true,
      timestamps: true,
    },
  },
  authConfig: {
    tokenExpiry: 2592000,
    secretKey: process.env.JWT_SECRET_KEY,
    hashSaltRounds: 8,
  },
  redisConfig: {
    host: process.env.REDIS_HOST,
    port: Number(process.env.REDIS_PORT),
  },
  secret: process.env.APP_SECRET,
  nodemailerConfig: {
    username: process.env.NODEMAILER_USERNAME,
    password: process.env.NODEMAILER_PASSWORD,
    fromEmail: process.env.NODEMAILER_FROM_EMAIL,
    host: process.env.NODEMAILER_EMAIL_HOST,
    port: 587,
  },
  notificationContactConfig: {
    contactDetails: 'support@blueverse.com',
    appName: 'blueverse',
    link: 'www.blueverse.com',
  },
  otpConfig: { otpExpiry: 1800 },
  feedbackBaseUrl: 'http:localhost:2000',
  washListProgressType: [
    'FEEDBACK_NOT_STARTED',
    'FEEDBACK_IN_PROGRESS',
    'FEEDBACK_COMPLETED',
  ],
  washListProgressTypeObject: {
    FEEDBACK_NOT_STARTED: 'FEEDBACK_NOT_STARTED',
    FEEDBACK_IN_PROGRESS: 'FEEDBACK_IN_PROGRESS',
    FEEDBACK_COMPLETED: 'FEEDBACK_COMPLETED',
  },
  authHeaderName: 'Authorization',
  superAdmin: {
    email: 'blueverse@gmail.com',
    password: 'Password@1',
  },
  userRoles: [
    'ADMIN',
    'FEEDBACK_AGENT',
    'SUB_ADMIN',
    'AREA_MANAGER',
    'OEM',
    'DEALER',
    'EMPLOYEE',
  ],
  userRolesObject: {
    ADMIN: 'ADMIN',
    FEEDBACK_AGENT: 'FEEDBACK_AGENT',
    SUB_ADMIN: 'SUB_ADMIN',
    AREA_MANAGER: 'AREA_MANAGER',
    OEM: 'OEM',
    DEALER: 'DEALER',
    EMPLOYEE: 'EMPLOYEE',
  },
  questionType: ['MULTIPLE_CHOICE', 'RATING', 'COMMENT'],
  questionTypeObject: {
    MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
    RATING: 'RATING',
    COMMENT: 'COMMENT',
  },
  SECRET_KEY_FOR_PASSWORD_FORGOT: 'secret_01@34',
  waterSaves: {
    GOLD: 140,
    SILVER: 150,
    PLATINUM: 200,
  },
  temporaryPassword: 'dealer@123dealert',
  actionType: {
    DELETE: 'DELETE',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
  },
  smsService: {
    SMS_API_KEY: process.env.SMS_API_KEY,
    SMS_SENDER_ID: process.env.SMS_SENDER_ID,
    SMS_SERVICE_NAME: process.env.SMS_SERVICE_NAME,
    SMS_BASE_URL: 'http://smsapi.24x7sms.com/api_2.0/SendSMS.aspx',
    OTP_VERIFICATION_KEYWORD: 'KYC_OTP_VERIFICATION',
  },
  cgstPercentage: 9,
  sgstPercentage: 9,
  machineWalletTransactionType: {
    ADDED: 'ADDED',
    DEBITED: 'DEBITED',
  },
  machineWalletSourceType: {
    WALLET: 'WALLET',
    CREDIT: 'CREDIT',
    TOPUP: 'TOPUP',
  },
  machineMemoStatusObject: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    FAILED: 'FAILED',
    PAID: 'PAID',
  },
  machineMemoStatusArr: ['PENDING', 'PROCESSING', 'FAILED', 'PAID'],
  machineMemoTypeArr: [
    'ADVANCE_MEMO',
    'TOPUP_MEMO',
    'TAX_INVOICE',
    'BLUEVERSE_CREDIT',
  ],
  machineMemoTypeObject: {
    ADVANCE_MEMO: 'ADVANCE_MEMO',
    TOPUP_MEMO: 'TOPUP_MEMO',
    TAX_INVOICE: 'TAX_INVOICE',
    BLUEVERSE_CREDIT: 'BLUEVERSE_CREDIT',
  },
  washType: {
    GOLD: 'GOLD',
    SILVER: 'SILVER',
    PLATINUM: 'PLATINUM',
  },
  washTypeArr: ['GOLD', 'SILVER', 'PLATINUM'],

  walletCSVType: {
    ALL_TRANSACTION: 'ALL_TRANSACTION',
    ONE_MACHINE_TRANSACTION: 'ONE_MACHINE_TRANSACTION',
    WALLET_BALANCE_TRANSACTION: 'WALLET_BALANCE_TRANSACTION',
    BLUEVERSECREDIT_BALANCE_TRANSACTION: 'BLUEVERSECREDIT_BALANCE_TRANSACTION',
  },
  walletCSVTypeArr: [
    'ALL_TRANSACTION',
    'ONE_MACHINE_TRANSACTION',
    'WALLET_BALANCE_TRANSACTION',
    'BLUEVERSECREDIT_BALANCE_TRANSACTION',
  ],

  whatsAppCredentials: {
    baseUrlBulk:
      'https://control.msg91.com/api/v5/whatsapp/whatsapp-outbound-message/bulk/',
    baseUrl: 'https://api.msg91.com/api/v5/whatsapp/whatsapp-outbound-message/',
    integrated_number: '917807977103',
    abandonedTemplateName: 'abandoned_feedback',
    feedbackSubmitTemplateName: 'feedback_submit ',
    defaultTemplateName: 'hello_world',
    language: {
      code: 'en_US',
      policy: 'deterministic',
    },
    type: 'template',
    content_type: 'template',
    messaging_product: 'whatsapp',
    authKey: process.env.WHATS_APP_AUTH_KEY,
  },
  payUPaymentGatewayCredentials: {
    merchantKey: process.env.PAYU_MERCHANT_KEY,
    merchantSaltKeyVersionOne: process.env.PAYU_MERCHANT_SALT_KEY_VERSION_ONE,
    productInfoObject: { WALLET: 'WALLET', TOPUP: 'TOPUP' },
    productInfoArr: ['WALLET', 'TOPUP'],
    ENVIRONMENT: process.env.ENVIRONMENT,
    status: { failure: 'failure', success: 'success', pending: 'pending' },
  },
  paymentTransactionStatusObject: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    FAILED: 'FAILED',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
  },
};

export { config };
